[package]
authors.workspace     = true
categories.workspace  = true
description.workspace = true
edition.workspace     = true
homepage.workspace    = true
keywords.workspace    = true
license.workspace     = true
readme                = "README.md"
repository.workspace  = true

include = ["src/**/*", "README.md"]
name    = "synd"
version = "0.1.0"

[dependencies]
synd-client = { path = "../synd_client", version = "0.1.0" }
synd-persistence = { path = "../synd_persistence", version = "0.1.0" }
synd-runtime = { path = "../synd_runtime", version = "0.1.0" }
synd-support = { path = "../synd_support", version = "0.1.0", features = ["conf", "humantime", "o11y"] }
synd-term = { path = "../synd_term", version = "0.3.2" }

anyhow             = { workspace = true }
clap               = { workspace = true, features = ["derive", "string", "color", "suggestions", "wrap_help", "env", "std"] }
either             = { workspace = true }
rustls             = { workspace = true }
schemars           = { workspace = true, features = ["derive"] }
serde              = { workspace = true, features = ["derive"] }
serde_json         = { workspace = true }
thiserror          = { workspace = true }
tokio              = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }
toml               = { workspace = true }
tracing            = { workspace = true }
tracing-appender   = "0.2.3"
tracing-subscriber = { workspace = true }
update-informer    = { version = "1.3.0", default-features = false, features = ["crates", "reqwest", "rustls-tls"] }

[features]
integration = ["synd-term/integration"]

[dev-dependencies]
assert_cmd = { workspace = true }
chrono     = { workspace = true }
crossterm  = "0.29.0"
fake       = { workspace = true }
futures-util = { workspace = true }
insta      = { workspace = true }
mockall    = { workspace = true }
octocrab   = { workspace = true, features = ["timeout", "tracing"] }
ratatui    = { version = "0.30.0", default-features = false, features = ["crossterm", "underline-color", "layout-cache"] }
synd-api   = { path = "../synd_api", version = "0.2.6" }
synd-auth  = { path = "../synd_auth", version = "0.2.5" }
synd-feed  = { path = "../synd_feed", version = "0.3.5" }
synd-registry = { path = "../synd_registry", version = "0.1.0" }
synd-test  = { path = "../synd_test" }
tempfile   = { workspace = true }
tokio      = { workspace = true, features = ["net"] }
tokio-util = { workspace = true }
url        = { workspace = true }

[lints]
workspace = true
