[package]
authors.workspace     = true
categories.workspace  = true
description.workspace = true
edition.workspace     = true
homepage.workspace    = true
keywords.workspace    = true
license.workspace     = true
readme                = "README.md"
repository.workspace  = true

include = ["src/**/*", "README.md"]
name    = "synd"
version.workspace = true

[dependencies]
synd-client      = { workspace = true }
synd-feed        = { workspace = true }
synd-persistence = { workspace = true }
synd-runtime     = { workspace = true }
synd-support     = { workspace = true, features = ["conf", "humantime", "o11y"] }
synd-term        = { workspace = true }

anyhow             = { workspace = true }
clap               = { workspace = true, features = ["derive", "string", "color", "suggestions", "wrap_help", "env", "std"] }
either             = { workspace = true }
rustls             = { workspace = true }
schemars           = { workspace = true, features = ["derive"] }
serde              = { workspace = true, features = ["derive"] }
serde_json         = { workspace = true }
thiserror          = { workspace = true }
tokio              = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }
toml               = { workspace = true }
tracing            = { workspace = true }
tracing-appender   = "0.2.5"
tracing-subscriber = { workspace = true }
update-informer    = { version = "1.3.0", default-features = false, features = ["crates", "reqwest", "rustls-tls"] }

[features]
integration = ["synd-term/integration"]

[dev-dependencies]
assert_cmd = { workspace = true }
chrono     = { workspace = true }
crossterm  = "0.29.0"
fake       = { workspace = true }
futures-util = { workspace = true }
insta      = { workspace = true }
mockall    = { workspace = true }
octocrab   = { workspace = true, features = ["timeout", "tracing"] }
ratatui    = { version = "0.30.2", default-features = false, features = ["crossterm", "underline-color", "layout-cache"] }
synd-api      = { workspace = true }
synd-auth     = { workspace = true }
synd-registry = { workspace = true }
synd-test     = { workspace = true }
tempfile   = { workspace = true }
tokio      = { workspace = true, features = ["net"] }
tokio-util = { workspace = true }
url        = { workspace = true }

[lints]
workspace = true

[package.metadata.dist]
dist    = true
formula = "synd"
