query Subscription($after: String, $first: Int) {
  output: subscription {
    feeds(after: $after, first: $first) {
      nodes {
        ...Feed
      }
      pageInfo {
        ...PageInfo
      }
    }
  }
}

fragment Feed on Feed {
  id
  title
  url
  updated
  websiteUrl
  description
  entries(first: 10) {
    nodes {
      ...EntryMeta
    }
  }
  links {
    nodes {
      ...Link
    }
  }
}

fragment EntryMeta on Entry {
    title,
    published,
    summary,
}

fragment Link on Link {
  href
  rel
  mediaType
  title  
}

query Entries($after: String, $first: Int!) {
  output: subscription {
    entries(after: $after, first: $first) {
      nodes {
        ...Entry
      }
      pageInfo {
        ...PageInfo
      }
    }
  }
}

fragment Entry on Entry {
  title
  published
  summary
  websiteUrl
  feed {
    ...FeedMeta
  }
}

fragment FeedMeta on FeedMeta {
  title
}

fragment PageInfo on PageInfo {
  hasNextPage
  endCursor
}
