[workspace]
members  = ["crates/synd*"]
resolver = "2"

[workspace.package]
authors     = ["ymgyt"]
categories  = ["command-line-utilities"]
description = "terminal feed viewer"
edition     = "2024"
homepage    = "https://docs.syndicationd.ymgyt.io/synd-term/"
keywords    = ["feed", "rss", "atom", "tui"]
license     = "MIT OR Apache-2.0"
readme      = "README.md"
repository  = "https://github.com/ymgyt/syndicationd"
version     = "0.4.0"

[workspace.dependencies]
synd-api         = { path = "crates/synd_api", version = "=0.4.0" }
synd-auth        = { path = "crates/synd_auth", version = "=0.4.0" }
synd-client      = { path = "crates/synd_client", version = "=0.4.0" }
synd-feed        = { path = "crates/synd_feed", version = "=0.4.0" }
synd-persistence = { path = "crates/synd_persistence", version = "=0.4.0" }
synd-protocol    = { path = "crates/synd_protocol", version = "=0.4.0" }
synd-registry    = { path = "crates/synd_registry", version = "=0.4.0" }
synd-runtime     = { path = "crates/synd_runtime", version = "=0.4.0" }
synd-support     = { path = "crates/synd_support", version = "=0.4.0" }
synd-term        = { path = "crates/synd_term", version = "=0.4.0" }
synd-test        = { path = "crates/synd_test" }

anyhow             = { version = "1", default-features = false, features = ["std"] }
assert_cmd         = { version = "2.1.2" }
async-graphql      = { version = "7.2.1" }
async-trait        = { version = "0.1.89", default-features = false }
axum               = { version = "0.8.9", default-features = false }
axum-server        = { version = "0.8.0", features = ["tls-rustls"] }
bitflags           = { version = "2.9.4", default-features = false }
bon                = { version = "3.9.1" }
bytes              = { version = "1.10.0" }
chrono             = { version = "0.4.44", default-features = false }
clap               = { version = "4.5", default-features = false }
criterion          = { version = "0.8.2", features = ["async_tokio"] }
derive_more        = { version = "2.1.1", default-features = false, features = ["from"] }
either             = { version = "1.15.0" }
fake               = { version = "5.1.0", features = ["derive", "chrono"] }
fdlimit            = { version = "0.3.0", default-features = false }
feed-rs            = { version = "2.4.0", default-features = false }
futures            = { version = "0.3.31" }
futures-util       = { version = "0.3.32", default-features = false }
graphql_client     = { version = "0.13.0", default-features = false }
headers            = { version = "0.4.1" }
http               = { version = "1.1" }
indexmap           = { version = "2.13.0" }
insta              = { version = "1.43" }
itertools          = { version = "0.14", default-features = false, features = ["use_std"] }
jsonwebtoken       = { version = "10.4.0", features = ["rust_crypto"] }
kvsd               = { version = "0.1.3", default-features = false }
mockall            = { version = "0.13.1" }
moka               = { version = "0.12.15", features = ["future"] }
nom                = { version = "8.0.0", default-features = false, features = ["std"] }
octocrab           = { version = "0.49.9", features = ["rustls-webpki-tokio"] }
pprof              = { version = "0.14", features = ["flamegraph"] }
proptest           = { version = "1.8.0" }
rand               = { version = "0.10.1" }
reqwest            = { version = "0.12.23", default-features = false, features = ["rustls-tls", "json"] }
rustls             = { version = "0.23.40", default-features = false, features = ["ring", "std", "tls12"] }
schemars           = { version = "0.8.21", default-features = false, features = ["derive"] }
serde              = { version = "1", features = ["derive"] }
serde_json         = { version = "1.0.149" }
sha2               = { version = "0.10" }
sqlx               = { version = "0.8.6", default-features = false }
strum              = { version = "0.28.0", features = ["derive"] }
tempfile           = { version = "3" }
thiserror          = { version = "2.0.18" }
tokio              = { version = "1.52.1", default-features = false }
tokio-util         = { version = "0.7.18" }
toml               = { version = "0.8.23" }
tracing            = { version = "0.1.41" }
tracing-subscriber = { version = "0.3.23", features = ["smallvec", "fmt", "ansi", "std", "env-filter", "time"], default-features = false }
url                = { version = "2.5.8" }
webpki-roots       = { version = "0.26.11" }
zstd               = { version = "0.13", default-features = false }

[profile.release]
panic = "abort"

[profile.bench]
# To enable framegraph
debug = true

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]

# cargo
cargo_common_metadata   = "warn"
multiple_crate_versions = "allow"
negative_feature_names  = "warn"
redundant_feature_names = "warn"
wildcard_dependencies   = "warn"

# pedantic
pedantic = { level = "warn", priority = -1 }

missing_errors_doc      = "allow"
missing_panics_doc      = "allow"
module_name_repetitions = "allow"
must_use_candidate      = "allow"

[workspace.metadata.crane]
# Required in crane buildDepsOnly derivation
name = "synd"

[workspace.metadata.release]
allow-branch            = ["main"]
rate-limit.new-packages = 7
shared-version          = true
tag-name                = "v{{version}}"

# The profile that 'cargo dist' will build with
[profile.dist]
codegen-units = 1
inherits      = "release"
lto           = true
panic         = "abort"
strip         = "symbols"
