# https://docs.codecov.com/docs/codecovyml-reference
coverage:
  round: down
  range: 50..80
  status: # https://docs.codecov.com/docs/commit-status
    project:
      default:
        target: auto # use the coverage from the base commit 
        threshold: 3% # allow the coverage to drop by
    patch:
      default:
        target: 50%
ignore:
  # On Codecov, it shows 300 lines being tracked, but in reality, there are only 3 lines.
  # These can be excluded in the report on llvm-cov.
  - "crates/synd_api/src/serve/layer/mod.rs"
  - "crates/synd_term/src/job.rs"
  - "crates/synd_ebpf_task"
  - "crates/synd_perf"
comment: # https://docs.codecov.com/docs/pull-request-comments
  # reach is not documented, but validator doesn't complain
  layout: "condensed_header,reach,diff,condensed_files,condensed_footer"
  hide_project_coverage: false
  require_changes: true
