{
 "title": "synd-api",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1h",
 "panels": [
  {
   "title": "Daily Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(http_server_request_total{job=\"syndicationd/synd-api\", instance=\"rpi4-03\"}[1d])",
     "legendFormat": "{{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Feed Subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "increase(feed_subscription_total{job=\"syndicationd/synd-api\"}[6m])",
     "legendFormat": "subscription"
    },
    {
     "expr": "increase(feed_unsubscription_total{job=\"syndicationd/synd-api\"}[6m])",
     "legendFormat": "unsubscription"
    }
   ]
  },
  {
   "title": "Weekly Unique Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(count_over_time({job=\"syndicationd/synd-api\"} | json | attributes_operation = \"FetchEntries\" and attributes_result = \"success\"[1w])) by (attributes_enduser_id))"
    }
   ]
  },
  {
   "title": "GraphQL Duration Histogram",
   "type": "bargauge",
   "description": "Latency Distribution",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(graphql_duration_seconds_bucket{job=\"syndicationd/synd-api\", instance=\"rpi4-03\"}[1d])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "GraphQL TaskMonitor Metrics",
   "type": "timeseries",
   "description": "tokio-metrics TaskMonitor metrics for graphql ",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(task_graphql_mean_poll_duration_total{job=\"syndicationd/synd-api\"}[$__rate_interval])",
     "legendFormat": "poll"
    },
    {
     "expr": "rate(task_graphql_mean_slow_poll_duration_total{job=\"syndicationd/synd-api\"}[$__rate_interval])",
     "legendFormat": "slow_poll"
    },
    {
     "expr": "rate(task_graphql_mean_idle_duration_total{job=\"syndicationd/synd-api\"}[$__rate_interval])",
     "legendFormat": "idle"
    },
    {
     "expr": "rate(task_graphql_mean_scheduled_duration_total{job=\"syndicationd/synd-api\"}[$__rate_interval])",
     "legendFormat": "scheduled"
    }
   ]
  },
  {
   "title": "Tokio Runtime Polls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(runtime_poll_total{job=\"syndicationd/synd-api\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tokio Runtime Busy Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(runtime_busy_duration_total{job=\"syndicationd/synd-api\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slow Request Traces ( > 500ms)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "filters": [
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "synd-api" ],
       "valueType": "string"
      },
      {
       "id": "e48f382a",
       "operator": "=",
       "scope": "resource",
       "tag": "deployment.environment",
       "value": [ "production" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [],
       "valueType": "string"
      },
      { "id": "duration-type", "value": "span" },
      {
       "id": "min-duration",
       "operator": ">",
       "tag": "duration",
       "value": "500ms",
       "valueType": "duration"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "{job=\"syndicationd/synd-api\", level=\"ERROR\"} |= ``"
    }
   ]
  },
  {
   "title": "Feed Cache Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "cache_feed_count{job=\"syndicationd/synd-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Feed Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cache_feed_size{instance=\"rpi4-03\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Health History",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum without (service_version) (target_info{job=\"syndicationd/synd-api\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}