[package]
edition = "2021"
name    = "synd-ebpf-common"
version = "0.1.0"

[features]
default = []
user    = ["aya"]

[target.'cfg(target_os = "linux")'.dependencies]
aya = { version = "0.12", optional = true }

[lib]
path = "src/lib.rs"
