[package]
authors.workspace    = true
categories.workspace = true
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
repository.workspace = true

description = "syndicationd backend api"
name        = "synd-api"
readme      = "README.md"
version.workspace = true

[dependencies]
synd-auth        = { workspace = true }
synd-feed        = { workspace = true, features = ["graphql"] }
synd-persistence = { workspace = true }
synd-protocol    = { workspace = true }
synd-registry    = { workspace = true }
synd-support     = { workspace = true, features = ["o11y"] }

async-graphql      = { workspace = true, features = ["tracing"] }
async-graphql-axum = { version = "7.2.1" }
axum               = { workspace = true, features = ["json"] }
axum-server        = { workspace = true }
chrono             = { workspace = true }
futures-util       = { workspace = true }
graphql_client     = { workspace = true }
moka               = { workspace = true, features = ["future"] }
pin-project        = "1.1.13"
reqwest            = { workspace = true }
serde              = { workspace = true }
tokio              = { workspace = true, features = ["macros", "net", "rt-multi-thread", "sync", "time"] }
tokio-metrics      = { version = "0.5.1", default-features = false, features = ["rt"] }
tokio-util         = { workspace = true }
tower              = { version = "0.5.3", default-features = false, features = ["limit", "timeout"] }
tower-http         = { version = "0.7.0", default-features = false, features = ["trace", "sensitive-headers", "cors", "limit"] }
tracing            = { workspace = true }
thiserror          = { workspace = true }

[features]
# Integration test
integration = []
# Enable graphql introspection
introspection        = []
opentelemetry-stdout = ["synd-support/opentelemetry-stdout"]

[dev-dependencies]
insta              = { workspace = true, features = ["yaml", "redactions"] }
tracing-subscriber = { workspace = true }

[lints]
workspace = true

[package.metadata.dist]
dist = false
