import '../.justfile'

pkg := "api"
database_url := "sqlite://" + source_directory() / "synd.db"

# List recipe
default:
    just --list

# Generate CHANGELOG for given version release 
changelog version:
    @nu {{script_dir}}/changelog.nu {{pkg}} {{version}}    

# Release crate
[no-cd]
release *flags:
    cargo release --package synd-{{pkg}} -v {{flags}}

prepare:
    pwd
    file synd.db
    cargo sqlx prepare --database-url {{database_url}}
