import '../.justfile'

database_url := "sqlite://" + source_directory() / "synd.db"

# List recipe
default:
    just --list

prepare:
    pwd
    file synd.db
    cargo sqlx prepare --database-url {{database_url}}
