import '../.justfile'

pkg := "kvsd"

# List recipe
default:
    just --list

# Generate CHANGELOG for given version release 
changelog version:
    @nu {{script_dir}}/changelog.nu {{pkg}} {{version}}    

# Release crate
[no-cd]
release *flags:
    cargo release --package synd-{{pkg}} -v {{flags}}
