set shell := ["nu", "-c"]

default:
    just --list

# Init terraform project
init *flags:
    terraform init {{flags}}

# Run terraform plan
plan *flags:
    terraform plan {{flags}}

# Run terraform apply
apply *flags:
    terraform apply {{flags}}
