mutation SubscribeFeed($input: SubscribeFeedInput!) {
  subscribeFeed(input: $input) {
    __typename
    ... on SubscribeFeedSuccess {
      feed {
        ...FeedMeta
      }
      status {
        code
      }
    }
    ... on SubscribeFeedError {
      status {
        code
      }
    }
  }
}

fragment FeedMeta on Feed {
  id
  title
  url
  updated
  websiteUrl
  description
  entries(first: 5) {
    nodes {
      ...EntryMeta
    }
  }
  links {
    nodes {
      ...Link
    }
  }
}

fragment EntryMeta on Entry {
    title,
    published,
    summary,
}

fragment Link on Link {
  href
  rel
  mediaType
  title  
}
