mutation SubscribeFeed($input: SubscribeFeedInput!) {
  subscribeFeed(input: $input) {
    __typename
    ... on SubscribeFeedSuccess {
      feed {
        ...FeedMeta
      }
      status {
        code
      }
    }
    ... on SubscribeFeedError {
      status {
        code
      }
    }
  }
}

fragment FeedMeta on Feed {
  id
  title
  url
  updated
  websiteUrl
  description
  links {
    nodes {
      ...Link
    }
  }
}

fragment Link on Link {
  href
  rel
  mediaType
  title  
}
