mutation SubscribeFeed($input: SubscribeFeedInput!) {
  subscribeFeed(input: $input) {
    __typename
    ... on SubscribeFeedSuccess {
      feed {
        title,
        url,
      }
      status {
        code
      }
    }
    ... on SubscribeFeedError {
      status {
        code
      }
    }
  }
}
