query Subscription($after: String, $first: Int) {
  output: subscription {
    feeds(after: $after, first: $first) {
      nodes {
        ...FeedMeta
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}

fragment FeedMeta on Feed {
  id
  title
  url
  updated
  links {
    nodes {
      ...Link
    }
  }
}

fragment Link on Link {
  href
  rel
  mediaType
  title  
}
