[advisories]
ignore = [
  # yaml-rust unmaintained, but serde_yaml use it
  "RUSTSEC-2024-0320",
  # https://github.com/ymgyt/syndicationd/issues/154
  "RUSTSEC-2024-0370",
  # paste unmaintained, wait for ratatui to update deps
  "RUSTSEC-2024-0436",

  # rsa used by sqlx
  "RUSTSEC-2023-0071",

  # adler unmaintaned
  "RUSTSEC-2025-0056",

  # rand is unsound with a custom logger using rand::rng()
  "RUSTSEC-2026-0097",

  # rustls-pemfile is pulled in via kvsd
  "RUSTSEC-2025-0134",

  # lru is pulled in via ratatui-core/layout-cache
  "RUSTSEC-2026-0002",

  # reqwest/rustls transitive chain
  "RUSTSEC-2026-0037",
  "RUSTSEC-2026-0044",
  "RUSTSEC-2026-0045",
  "RUSTSEC-2026-0046",
  "RUSTSEC-2026-0047",
  "RUSTSEC-2026-0048",
  "RUSTSEC-2026-0049",
  "RUSTSEC-2026-0098",
  "RUSTSEC-2026-0099",
  "RUSTSEC-2026-0104",
]

[yanked]
# in derivations we could not connect net
# crate-audit> error: couldn't check if the package is yanked: not found: No such crate in crates.io index: foo
enabled      = false
update_index = false
