[package]
authors.workspace    = true
categories.workspace = true
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
repository.workspace = true

description = "Feed lifecycle registry"
name        = "synd-registry"
readme      = "README.md"
version     = "0.1.0"

[dependencies]
synd-feed = { path = "../synd_feed", version = "0.3.5" }

anyhow      = { workspace = true }
chrono      = { workspace = true, features = ["serde"] }
rand        = { workspace = true }
serde       = { workspace = true }
serde_json  = { workspace = true }
thiserror   = { workspace = true }
tokio       = { workspace = true, features = ["sync", "time", "rt", "macros"] }
tokio-util  = { workspace = true }
tracing     = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }

[lints]
workspace = true
