[package]
authors.workspace    = true
categories.workspace = true
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
repository.workspace = true

description = "Feed lifecycle registry"
name        = "synd-registry"
readme      = "README.md"
version.workspace = true

[dependencies]
synd-feed    = { workspace = true }
synd-support = { workspace = true }

bon         = { workspace = true }
chrono      = { workspace = true, features = ["serde"] }
derive_more = { workspace = true }
rand        = { workspace = true }
serde       = { workspace = true }
serde_json  = { workspace = true }
strum       = { workspace = true }
thiserror   = { workspace = true }
tokio       = { workspace = true, features = ["sync", "time", "rt", "macros"] }
tokio-util  = { workspace = true }
tracing     = { workspace = true }

[features]
default = []
test    = []

[dev-dependencies]
anyhow = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }

[lints]
workspace = true
