[package]
authors.workspace     = true
categories.workspace  = true
description           = "Terminal application library for syndicationd"
edition.workspace     = true
homepage.workspace    = true
keywords.workspace    = true
license.workspace     = true
readme                = "README.md"
repository.workspace  = true

include = ["src/**/*", "gql/**/*", "categories.toml", "README.md"]
name    = "synd-term"
version.workspace = true

[dependencies]
synd-auth    = { workspace = true }
synd-client  = { workspace = true }
synd-feed    = { workspace = true, features = ["fake", "jsonschema"] }
synd-support = { workspace = true, features = ["humantime", "conf", "o11y"] }

anyhow               = { workspace = true }
chrono               = { workspace = true, features = ["std", "now", "serde", "clock"] }
chrono-humanize      = "0.2.3"
crossterm            = { version = "0.29.0", features = ["event-stream"] }
edit                 = "0.1.5"
futures-util         = { workspace = true }
graphql_client       = { workspace = true, features = ["graphql_query_derive"] }
html2text            = { version = "0.17.1" }
indexmap             = { workspace = true }
itertools            = { workspace = true }
nom                  = { workspace = true }
nom-language         = "0.1.0"
nucleo               = "0.5.0"
octocrab             = { workspace = true, features = ["timeout", "tracing"] }
open                 = "5.4.0"
ratatui              = { version = "0.30.2", default-features = false, features = ["crossterm", "underline-color", "layout-cache"] }
schemars             = { workspace = true, features = ["derive"] }
serde                = { workspace = true, features = ["derive"] }
serde_json           = "1.0.151"
thiserror            = { workspace = true }
tokio                = { workspace = true, features = ["macros", "net", "rt-multi-thread", "sync", "time"] }
tokio-stream         = { version = "0.1.19", optional = true }
toml                 = { workspace = true }
tracing              = { workspace = true }
tui-widgets          = { version = "0.7.10", default-features = false, features = ["big-text"] }
unicode-segmentation = "1.13.3"
url                  = { workspace = true }

[features]
# Integration test
integration = ["dep:tokio-stream"]

[dev-dependencies]
synd-client = { workspace = true, features = ["fake"] }

criterion   = { workspace = true }
fake        = { workspace = true }
insta       = { workspace = true }
pprof       = { workspace = true }
proptest    = { workspace = true }
tempfile    = { workspace = true }

[[bench]]
harness = false
name    = "render"
required-features = ["integration"]

[lints]
workspace = true
