[package]
authors.workspace     = true
categories.workspace  = true
description.workspace = true
edition.workspace     = true
homepage.workspace    = true
keywords.workspace    = true
license.workspace     = true
readme.workspace      = true
repository.workspace  = true

include = ["src/**/*", "gql/**/*", "CHANGELOG.md", "categories.toml"]
name    = "synd-term"
version = "0.3.2"

[dependencies]
synd-auth = { path = "../synd_auth", version = "0.2.5" }
synd-client = { path = "../synd_client", version = "0.1.0" }
synd-feed = { path = "../synd_feed", version = "0.3.5", features = ["fake", "jsonschema"] }
synd-support = { path = "../synd_support", version = "0.1.0", features = ["humantime", "conf", "o11y"] }

anyhow               = { workspace = true }
chrono               = { workspace = true, features = ["std", "now", "serde", "clock"] }
chrono-humanize      = "0.2.3"
crossterm            = { version = "0.29.0", features = ["event-stream"] }
edit                 = "0.1.5"
either               = { workspace = true }
futures-util         = { workspace = true, features = ["sink"] }
graphql_client       = { workspace = true, features = ["graphql_query_derive"] }
html2text            = { version = "0.17.1" }
itertools            = { workspace = true }
nom                  = { workspace = true }
nom-language         = "0.1.0"
nucleo               = "0.5.0"
octocrab             = { workspace = true, features = ["timeout", "tracing"] }
open                 = "5.3.2"
ratatui              = { version = "0.30.1", default-features = false, features = ["crossterm", "underline-color", "layout-cache"] }
schemars             = { workspace = true, features = ["derive"] }
serde                = { workspace = true, features = ["derive"] }
serde_json           = "1.0.149"
thiserror            = { workspace = true }
tokio                = { workspace = true, features = ["macros", "net", "rt-multi-thread", "sync", "time"] }
tokio-tungstenite    = { version = "0.29.0", default-features = false, features = ["connect"] }
tokio-stream         = { version = "0.1.18", optional = true }
toml                 = { workspace = true }
tracing              = { workspace = true }
tui-widgets          = { version = "0.7.2", default-features = false, features = ["big-text"] }
unicode-segmentation = "1.12.0"
url                  = { workspace = true }

[features]
# Integration test
integration = ["dep:tokio-stream"]

[dev-dependencies]
synd-client = { path = "../synd_client", version = "0.1.0", features = ["fake"] }

criterion   = { workspace = true }
fake        = { workspace = true }
insta       = { workspace = true }
pprof       = { workspace = true }
proptest    = { workspace = true }
tempfile    = { workspace = true }

[[bench]]
harness = false
name    = "render"
required-features = ["integration"]

[lints]
workspace = true

[package.metadata.release]
pre-release-hook = ["just", "changelog", "{{version}}"]

pre-release-replacements = [
  { file = "CHANGELOG.md", search = "unreleased", replace = "v{{version}}", min = 0 },
  { file = "CHANGELOG.md", search = "__release_date__", replace = "{{date}}", min = 0 },
  { file = "README.md", search = "/synd-term-v.*/", replace = "/{{crate_name}}-v{{version}}/", min = 0 },
  { file = "README.md", search = "/synd-term-v.*", replace = "/{{crate_name}}-v{{version}}", min = 0 },
]
tag-message = "chore: release {{crate_name}} version {{version}}"

[package.metadata.dist]
dist    = true
formula = "synd-term"
