mutation SubscribeFeed($input: SubscribeFeedInput!) {
  subscribeFeed(input: $input) {
    status {
      code
    }
    url
    disposition
  }
}

mutation UnsubscribeFeed($input: UnsubscribeFeedInput!) {
  unsubscribeFeed(input: $input) {
    status {
      code
    }
    url
    disposition
  }
}

mutation RefreshFeed($input: RefreshFeedInput!) {
  refreshFeed(input: $input) {
    status {
      code
    }
    requestId
    disposition
  }
}
